# -*- coding: utf-8 -*-
"""Ques2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHIVTGi2kI--UaDNHp0Euq3vq4AufyZO

#Question 2: Lists & Dictionaries
"""

def group_by_length(strings):
    grouped = {}
    for s in strings:
        length = len(s)
        if length not in grouped:
            grouped[length] = []
        grouped[length].append(s)
    return dict(sorted(grouped.items()))

# Test cases
print(group_by_length(["apple", "bat", "car", "elephant", "dog", "bear"]))

