# -*- coding: utf-8 -*-
"""Ques7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHIVTGi2kI--UaDNHp0Euq3vq4AufyZO

#Question 8: Time Check
"""

import pandas as pd

def check_time_coverage(df):
    df['start_datetime'] = pd.to_datetime(df['startDay'] + ' ' + df['startTime'], errors='coerce', format='%A %H:%M:%S')
    df['end_datetime'] = pd.to_datetime(df['endDay'] + ' ' + df['endTime'], errors='coerce', format='%A %H:%M:%S')

    result = {}

    for (id_, id_2), group in df.groupby(['id', 'id_2']):
        days_covered = pd.to_datetime(group['startDay'], format='%A', errors='coerce').dt.weekday.unique()
        time_coverage = group[['start_datetime', 'end_datetime']]

        full_week_coverage = set(days_covered) == set(range(7))

        full_day_coverage = False
        if not time_coverage.isnull().values.any():
            time_coverage = time_coverage.sort_values('start_datetime')
            total_seconds_covered = 0

            for _, row in time_coverage.iterrows():
                total_seconds_covered += (row['end_datetime'] - row['start_datetime']).total_seconds()

            full_day_coverage = total_seconds_covered >= 86400

        result[(id_, id_2)] = full_week_coverage and full_day_coverage

    return pd.Series(result)

# Example usage
df = pd.read_csv('/content/dataset-1.csv')
result = check_time_coverage(df)
print(result)

