# -*- coding: utf-8 -*-
"""Ques7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHIVTGi2kI--UaDNHp0Euq3vq4AufyZO

#Question 7: Matrix Rotation and Transformation
"""

import numpy as np

def rotate_and_transform(matrix):

    rotated_matrix = np.rot90(matrix, -1)


    transformed_matrix = []
    for i in range(len(rotated_matrix)):
        row = []
        for j in range(len(rotated_matrix[i])):
            row_sum = sum(rotated_matrix[i]) - rotated_matrix[i][j]
            col_sum = sum(rotated_matrix[:, j]) - rotated_matrix[i][j]
            row.append(row_sum + col_sum)
        transformed_matrix.append(row)

    return np.array(transformed_matrix)

# Example usage
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result = rotate_and_transform(np.array(matrix))
print(result)



