# -*- coding: utf-8 -*-
"""Ques7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHIVTGi2kI--UaDNHp0Euq3vq4AufyZO

#Question 9: Distance Matrix Calculation
"""

import pandas as pd
import numpy as np

def calculate_distance_matrix(df):
    num_points = df.shape[0]
    matrix = pd.DataFrame(np.zeros((num_points, num_points)), index=df.index, columns=df.index)

    for i in range(num_points):
        for j in range(num_points):
            matrix.iloc[i, j] = np.linalg.norm(df.iloc[i] - df.iloc[j])

    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError(f"Distance matrix is not square: {matrix.shape}")

    matrix = matrix + matrix.T - np.diag(matrix.values.diagonal())

    if matrix.shape[0] != num_points:
        raise ValueError(f"Final distance matrix shape mismatch: expected {num_points}, got {matrix.shape[0]}")

    return matrix

# Example usage
df = pd.read_csv('/content/dataset-2.csv')
distance_matrix = calculate_distance_matrix(df)
print(distance_matrix)

