# -*- coding: utf-8 -*-
"""Ques7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHIVTGi2kI--UaDNHp0Euq3vq4AufyZO

#Question 10: Unroll Distance Matrix
"""

def unroll_distance_matrix(df):
    # Unroll the matrix into a DataFrame
    unrolled_df = df.stack().reset_index()
    unrolled_df.columns = ['id_start', 'id_end', 'distance']
    return unrolled_df

# Example usage
unrolled_df = unroll_distance_matrix(distance_matrix)
print(unrolled_df)

