# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHIVTGi2kI--UaDNHp0Euq3vq4AufyZO

#Question 1: Reverse List by N Elements
"""

def reverse_by_n(lst, n):
    result = []
    for i in range(0, len(lst), n):
        group = lst[i:i+n]
        for j in range(len(group)-1, -1, -1):
            result.append(group[j])
    return result

# Test cases
print(reverse_by_n([1, 2, 3, 4, 5, 6, 7, 8], 3))

