# -*- coding: utf-8 -*-
"""Ques4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHIVTGi2kI--UaDNHp0Euq3vq4AufyZO

#Question 4: Generate Unique Permutations
"""

from itertools import permutations

def unique_permutations(lst):
    return [list(p) for p in set(permutations(lst))]

print(unique_permutations([1, 1, 2]))

