# -*- coding: utf-8 -*-
"""Ques7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHIVTGi2kI--UaDNHp0Euq3vq4AufyZO

#Question 11: Finding IDs within Percentage Threshold
"""

import pandas as pd

def find_ids_within_ten_percentage_threshold(df, reference_id):
    if df.empty:
        raise ValueError("The DataFrame is empty. Please provide a valid DataFrame.")

    avg_distance = df[df['id_start'] == reference_id]['distance'].mean()

    if pd.isna(avg_distance):
        raise ValueError(f"No distance data found for reference_id: {reference_id}")

    lower_bound = avg_distance * 0.9
    upper_bound = avg_distance * 1.1

    result = df[(df['distance'] >= lower_bound) & (df['distance'] <= upper_bound)]['id_start'].unique()

    return sorted(result)

try:
    ids_within_threshold = find_ids_within_ten_percentage_threshold(unrolled_df, reference_id=5)
    print(ids_within_threshold)
except ValueError as e:
    print(e)

